### 1.Which apps have the highest rating in the given available dataset?
SELECT [App],[Rating]
FROM [dbo].[cleaned_file$]
ORDER BY [Rating] DESC

### 2.What are the number of installs and reviews for the above apps? Return the apps with the highest reviews to the top.
SELECT [App],[Reviews],[Installs]
FROM [dbo].[cleaned_file$]
ORDER BY [Reviews] DESC

### 3.Which app has the highest number of reviews? Also, mention the number of reviews and category of the app
SELECT [App],[Category],[Reviews]
FROM [dbo].[cleaned_file$]
ORDER BY [Reviews] DESC

### 4.What is the total amount of revenue generated by the google play store by hosting apps? 
(Whenever a user buys apps  from the google play store, the amount is considered in the revenue)
SELECT SUM([Price])
FROM [dbo].[cleaned_file$]


### 5. Which Category of google play store apps has the highest number of installs?
also, find out the total number of installs for that particular category.
SELECT [App],[Installs]
FROM [dbo].[cleaned_file$]
ORDER BY [Installs] DESC

### 6.Which Genre has the most number of published apps?
SELECT [App],[Genres]
FROM [dbo].[cleaned_file$]
ORDER BY [Genres] DESC

### 7.Provide the list of all games ordered in such a way that the game that has the highest number of installs is displayed on the top
(to avoid duplicate results use distinct)
SELECT DISTINCT [App],[Category],[Installs]
FROM [dbo].[cleaned_file$]
WHERE [Category] = 'GAME'
ORDER BY [Installs] DESC

### 8.Provide the list of apps that can work on android version 4.0.3 and UP.
SELECT [App],[Android Ver]
FROM [dbo].[cleaned_file$]
WHERE [Android Ver] LIKE '4.0.3 and up'

### 9. How many apps from the given data set are free? Also, provide the number of paid apps.
SELECT [App],[Type]
FROM [dbo].[cleaned_file$]
WHERE [Type] = 'Free'
### 9b
SELECT [App],[Type]
FROM [dbo].[cleaned_file$]
WHERE [Type] = 'Paid'

### 10. Which is the best dating app? (Best dating app is the one having the highest number of Reviews)
SELECT [App],[Category],[Reviews]
FROM [dbo].[cleaned_file$]
WHERE [Category] = 'DATING'
ORDER BY [Reviews] DESC

### 11. Get the number of reviews having positive sentiment and number of reviews having negative sentiment 
for the app 10 best foods for you and compare them.
SELECT [App],[Sentiment]
FROM [dbo].[cleaned_playstore_reviews$]
 

### 12.Which comments of ASUS SuperNote have sentiment polarity and sentiment subjectivity both as 1?
SELECT [App],[Sentiment_Polarity],[Sentiment_Subjectivity]
FROM [dbo].[cleaned_playstore_reviews$]
WHERE ([Sentiment_Polarity] = 1) AND ([Sentiment_Subjectivity] = 1)

### 13.Get all the neutral sentiment reviews for the app Abs Training-Burn belly fat 
SELECT [App],[Sentiment]
FROM [dbo].[cleaned_playstore_reviews$]
WHERE ([App] = 'Abs Training-Burn belly fat') AND ([Sentiment] = 'NEUTRAL') 

### 14. Extract all negative sentiment reviews for Adobe Acrobat Reader with their sentiment polarity and sentiment subjectivity
 SELECT [App],[Sentiment],[Sentiment_Polarity],[Sentiment_Subjectivity]
 FROM [dbo].[cleaned_playstore_reviews$]
  WHERE ([App] = 'Adobe Acrobat Reader') AND ([Sentiment] = 'NEGATIVE')
